package com.isongshu.huishou.skeleton.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("code", "id", Code.class);
		arp.addMapping("news_info", "id", NewsInfo.class);
		arp.addMapping("order_info", "id", OrderInfo.class);
		arp.addMapping("other_big_recycle", "id", OtherBigRecycle.class);
		arp.addMapping("other_join", "id", OtherJoin.class);
		arp.addMapping("other_new_product", "id", OtherNewProduct.class);
		arp.addMapping("prd_clazz_brand", "id", PrdClazzBrand.class);
		arp.addMapping("prd_package", "id", PrdPackage.class);
		// Composite Primary Key order: id,packageId
		arp.addMapping("prd_package_item", "id,packageId", PrdPackageItem.class);
		arp.addMapping("prd_product", "id", PrdProduct.class);
		arp.addMapping("sys_admin", "id", SysAdmin.class);
		arp.addMapping("sys_param", "id", SysParam.class);
		arp.addMapping("user", "id", User.class);
	}
}

