package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseCmsLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("CmsLinkDao")
public class CmsLink extends BaseCmsLink<CmsLink> {
	public static final CmsLink dao = new CmsLink();
}
