package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("CodeDao")
public class Code extends BaseCode<Code> {
	public static final Code dao = new Code();
}
