package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseCommentInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("CommentInfoDao")
public class CommentInfo extends BaseCommentInfo<CommentInfo> {
	public static final CommentInfo dao = new CommentInfo();
}
