package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseNewsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("NewsInfoDao")
public class NewsInfo extends BaseNewsInfo<NewsInfo> {
	public static final NewsInfo dao = new NewsInfo();
}
