package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseOrderInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("OrderInfoDao")
public class OrderInfo extends BaseOrderInfo<OrderInfo> {
	public static final OrderInfo dao = new OrderInfo();
}
