package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseOtherJoin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("OtherJoinDao")
public class OtherJoin extends BaseOtherJoin<OtherJoin> {
	public static final OtherJoin dao = new OtherJoin();
}
