package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseOtherNewProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("OtherNewProductDao")
public class OtherNewProduct extends BaseOtherNewProduct<OtherNewProduct> {
	public static final OtherNewProduct dao = new OtherNewProduct();
}
