package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseOtherBigRecycle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("OtherBigRecycleDao")
public class OtherBigRecycle extends BaseOtherBigRecycle<OtherBigRecycle> {
	public static final OtherBigRecycle dao = new OtherBigRecycle();
}
