package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BasePrdClazzBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("PrdClazzBrandDao")
public class PrdClazzBrand extends BasePrdClazzBrand<PrdClazzBrand> {
	public static final PrdClazzBrand dao = new PrdClazzBrand();
}
