package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BasePrdPackage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("PrdPackageDao")
public class PrdPackage extends BasePrdPackage<PrdPackage> {
	public static final PrdPackage dao = new PrdPackage();
}
