package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BasePrdPackageItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("PrdPackageItemDao")
public class PrdPackageItem extends BasePrdPackageItem<PrdPackageItem> {
	public static final PrdPackageItem dao = new PrdPackageItem();
}
