package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BasePrdProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("PrdProductDao")
public class PrdProduct extends BasePrdProduct<PrdProduct> {
	public static final PrdProduct dao = new PrdProduct();

	
	
}
