package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseSysAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("SysAdminDao")
public class SysAdmin extends BaseSysAdmin<SysAdmin> {
	public static final SysAdmin dao = new SysAdmin();
}
