package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseSysParam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("SysParamDao")
public class SysParam extends BaseSysParam<SysParam> {
	public static final SysParam dao = new SysParam();
}
