package com.isongshu.huishou.skeleton.model;

import org.springframework.stereotype.Service;

import com.isongshu.huishou.skeleton.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Service("UserDao")
public class User extends BaseUser<User> {
	public static final User dao = new User();
}
