package com.isongshu.huishou.skeleton.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderSelItem<M extends BaseOrderSelItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public String getIdColumnName() {
		return "id";
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("orderId", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("orderId");
	}

	public String getOrderIdColumnName() {
		return "orderId";
	}

	public void setDefaultVlaue(java.lang.Float defaultVlaue) {
		set("defaultVlaue", defaultVlaue);
	}

	public java.lang.Float getDefaultVlaue() {
		return get("defaultVlaue");
	}

	public String getDefaultVlaueColumnName() {
		return "defaultVlaue";
	}

	public void setItemName(java.lang.String itemName) {
		set("itemName", itemName);
	}

	public java.lang.String getItemName() {
		return get("itemName");
	}

	public String getItemNameColumnName() {
		return "itemName";
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
	}

	public java.lang.Integer getParentId() {
		return get("parentId");
	}

	public String getParentIdColumnName() {
		return "parentId";
	}

	public void setIsSel(java.lang.String isSel) {
		set("isSel", isSel);
	}

	public java.lang.String getIsSel() {
		return get("isSel");
	}

	public String getIsSelColumnName() {
		return "isSel";
	}

}
