package com.isongshu.huishou.skeleton.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderInfo<M extends BaseOrderInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public String getIdColumnName() {
		return "id";
	}

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}

	public java.lang.String getOrderId() {
		return get("orderId");
	}

	public String getOrderIdColumnName() {
		return "orderId";
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public String getUserNameColumnName() {
		return "userName";
	}

	public void setContactName(java.lang.String contactName) {
		set("contactName", contactName);
	}

	public java.lang.String getContactName() {
		return get("contactName");
	}

	public String getContactNameColumnName() {
		return "contactName";
	}

	public void setContactTel(java.lang.String contactTel) {
		set("contactTel", contactTel);
	}

	public java.lang.String getContactTel() {
		return get("contactTel");
	}

	public String getContactTelColumnName() {
		return "contactTel";
	}

	public void setPayType(java.lang.String payType) {
		set("payType", payType);
	}

	public java.lang.String getPayType() {
		return get("payType");
	}

	public String getPayTypeColumnName() {
		return "payType";
	}

	public void setPayBankCode(java.lang.String payBankCode) {
		set("payBankCode", payBankCode);
	}

	public java.lang.String getPayBankCode() {
		return get("payBankCode");
	}

	public String getPayBankCodeColumnName() {
		return "payBankCode";
	}

	public void setPayBankAccountName(java.lang.String payBankAccountName) {
		set("payBankAccountName", payBankAccountName);
	}

	public java.lang.String getPayBankAccountName() {
		return get("payBankAccountName");
	}

	public String getPayBankAccountNameColumnName() {
		return "payBankAccountName";
	}

	public void setPayBankAccountNum(java.lang.String payBankAccountNum) {
		set("payBankAccountNum", payBankAccountNum);
	}

	public java.lang.String getPayBankAccountNum() {
		return get("payBankAccountNum");
	}

	public String getPayBankAccountNumColumnName() {
		return "payBankAccountNum";
	}

	public void setPayOtherAccount(java.lang.String payOtherAccount) {
		set("payOtherAccount", payOtherAccount);
	}

	public java.lang.String getPayOtherAccount() {
		return get("payOtherAccount");
	}

	public String getPayOtherAccountColumnName() {
		return "payOtherAccount";
	}

	public void setRecycleType(java.lang.String recycleType) {
		set("recycleType", recycleType);
	}

	public java.lang.String getRecycleType() {
		return get("recycleType");
	}

	public String getRecycleTypeColumnName() {
		return "recycleType";
	}

	public void setRecycleTradeAddress(java.lang.String recycleTradeAddress) {
		set("recycleTradeAddress", recycleTradeAddress);
	}

	public java.lang.String getRecycleTradeAddress() {
		return get("recycleTradeAddress");
	}

	public String getRecycleTradeAddressColumnName() {
		return "recycleTradeAddress";
	}

	public void setRecycleTradeAddressCity(java.lang.String recycleTradeAddressCity) {
		set("recycleTradeAddressCity", recycleTradeAddressCity);
	}

	public java.lang.String getRecycleTradeAddressCity() {
		return get("recycleTradeAddressCity");
	}

	public String getRecycleTradeAddressCityColumnName() {
		return "recycleTradeAddressCity";
	}

	public void setRecycleTradeTime(java.util.Date recycleTradeTime) {
		set("recycleTradeTime", recycleTradeTime);
	}

	public java.util.Date getRecycleTradeTime() {
		return get("recycleTradeTime");
	}

	public String getRecycleTradeTimeColumnName() {
		return "recycleTradeTime";
	}

	public void setRecycleExpress(java.lang.String recycleExpress) {
		set("recycleExpress", recycleExpress);
	}

	public java.lang.String getRecycleExpress() {
		return get("recycleExpress");
	}

	public String getRecycleExpressColumnName() {
		return "recycleExpress";
	}

	public void setRecycleExpressCode(java.lang.String recycleExpressCode) {
		set("recycleExpressCode", recycleExpressCode);
	}

	public java.lang.String getRecycleExpressCode() {
		return get("recycleExpressCode");
	}

	public String getRecycleExpressCodeColumnName() {
		return "recycleExpressCode";
	}

	public void setPrdProductId(java.lang.Integer prdProductId) {
		set("prdProductId", prdProductId);
	}

	public java.lang.Integer getPrdProductId() {
		return get("prdProductId");
	}

	public String getPrdProductIdColumnName() {
		return "prdProductId";
	}

	public void setPrdProductName(java.lang.String prdProductName) {
		set("prdProductName", prdProductName);
	}

	public java.lang.String getPrdProductName() {
		return get("prdProductName");
	}

	public String getPrdProductNameColumnName() {
		return "prdProductName";
	}

	public void setAssessPrice(java.lang.Integer assessPrice) {
		set("assessPrice", assessPrice);
	}

	public java.lang.Integer getAssessPrice() {
		return get("assessPrice");
	}

	public String getAssessPriceColumnName() {
		return "assessPrice";
	}

	public void setTradePrice(java.lang.Integer tradePrice) {
		set("tradePrice", tradePrice);
	}

	public java.lang.Integer getTradePrice() {
		return get("tradePrice");
	}

	public String getTradePriceColumnName() {
		return "tradePrice";
	}

	public void setMachinePassword(java.lang.String machinePassword) {
		set("machinePassword", machinePassword);
	}

	public java.lang.String getMachinePassword() {
		return get("machinePassword");
	}

	public String getMachinePasswordColumnName() {
		return "machinePassword";
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public String getStatusColumnName() {
		return "status";
	}

	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}

	public java.lang.String getDetail() {
		return get("detail");
	}

	public String getDetailColumnName() {
		return "detail";
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public String getRemarkColumnName() {
		return "remark";
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public String getCreateTimeColumnName() {
		return "createTime";
	}

	public void setCreateUser(java.lang.String createUser) {
		set("createUser", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("createUser");
	}

	public String getCreateUserColumnName() {
		return "createUser";
	}

}
