package com.isongshu.huishou.skeleton.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCmsLink<M extends BaseCmsLink<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public String getIdColumnName() {
		return "id";
	}

	public void setLinkName(java.lang.String linkName) {
		set("linkName", linkName);
	}

	public java.lang.String getLinkName() {
		return get("linkName");
	}

	public String getLinkNameColumnName() {
		return "linkName";
	}

	public void setLinkType(java.lang.String linkType) {
		set("linkType", linkType);
	}

	public java.lang.String getLinkType() {
		return get("linkType");
	}

	public String getLinkTypeColumnName() {
		return "linkType";
	}

	public void setLinkUrl(java.lang.String linkUrl) {
		set("linkUrl", linkUrl);
	}

	public java.lang.String getLinkUrl() {
		return get("linkUrl");
	}

	public String getLinkUrlColumnName() {
		return "linkUrl";
	}

	public void setIconUrl(java.lang.String iconUrl) {
		set("iconUrl", iconUrl);
	}

	public java.lang.String getIconUrl() {
		return get("iconUrl");
	}

	public String getIconUrlColumnName() {
		return "iconUrl";
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public String getRemarkColumnName() {
		return "remark";
	}

	public void setOrderby(java.lang.Integer orderby) {
		set("orderby", orderby);
	}

	public java.lang.Integer getOrderby() {
		return get("orderby");
	}

	public String getOrderbyColumnName() {
		return "orderby";
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public String getCreateTimeColumnName() {
		return "createTime";
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}

	public java.lang.String getIsvalid() {
		return get("isvalid");
	}

	public String getIsvalidColumnName() {
		return "isvalid";
	}

}
