package com.isongshu.huishou.skeleton.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserOrder<M extends BaseUserOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public String getIdColumnName() {
		return "id";
	}

	public void setProductTypeId(java.lang.Integer productTypeId) {
		set("product_type_id", productTypeId);
	}

	public java.lang.Integer getProductTypeId() {
		return get("product_type_id");
	}

	public String getProductTypeIdColumnName() {
		return "product_type_id";
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customer_id");
	}

	public String getCustomerIdColumnName() {
		return "customer_id";
	}

	public void setCustomerName(java.lang.String customerName) {
		set("customer_name", customerName);
	}

	public java.lang.String getCustomerName() {
		return get("customer_name");
	}

	public String getCustomerNameColumnName() {
		return "customer_name";
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public String getPhoneColumnName() {
		return "phone";
	}

	public void setRebackType(java.lang.Integer rebackType) {
		set("reback_type", rebackType);
	}

	public java.lang.Integer getRebackType() {
		return get("reback_type");
	}

	public String getRebackTypeColumnName() {
		return "reback_type";
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public String getStatusColumnName() {
		return "status";
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public String getCityColumnName() {
		return "city";
	}

	public void setPrice(java.lang.Float price) {
		set("price", price);
	}

	public java.lang.Float getPrice() {
		return get("price");
	}

	public String getPriceColumnName() {
		return "price";
	}

	public void setDescriptSelItem(java.lang.String descriptSelItem) {
		set("descript_sel_item", descriptSelItem);
	}

	public java.lang.String getDescriptSelItem() {
		return get("descript_sel_item");
	}

	public String getDescriptSelItemColumnName() {
		return "descript_sel_item";
	}

	public void setInputDate(java.lang.String inputDate) {
		set("inputDate", inputDate);
	}

	public java.lang.String getInputDate() {
		return get("inputDate");
	}

	public String getInputDateColumnName() {
		return "inputDate";
	}

}
