package com.isongshu.huishou.skeleton.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderFile<M extends BaseOrderFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public String getIdColumnName() {
		return "id";
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("orderId", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("orderId");
	}

	public String getOrderIdColumnName() {
		return "orderId";
	}

	public void setFileName(java.lang.String fileName) {
		set("fileName", fileName);
	}

	public java.lang.String getFileName() {
		return get("fileName");
	}

	public String getFileNameColumnName() {
		return "fileName";
	}

	public void setFilePath(java.lang.String filePath) {
		set("filePath", filePath);
	}

	public java.lang.String getFilePath() {
		return get("filePath");
	}

	public String getFilePathColumnName() {
		return "filePath";
	}

	public void setUploadDate(java.lang.String uploadDate) {
		set("uploadDate", uploadDate);
	}

	public java.lang.String getUploadDate() {
		return get("uploadDate");
	}

	public String getUploadDateColumnName() {
		return "uploadDate";
	}

}
