package com.isongshu.huishou.skeleton.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommentInfo<M extends BaseCommentInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public String getIdColumnName() {
		return "id";
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public String getUserNameColumnName() {
		return "userName";
	}

	public void setContactTel(java.lang.String contactTel) {
		set("contactTel", contactTel);
	}

	public java.lang.String getContactTel() {
		return get("contactTel");
	}

	public String getContactTelColumnName() {
		return "contactTel";
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public String getContentColumnName() {
		return "content";
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public String getCreateTimeColumnName() {
		return "createTime";
	}

	public void setScore(java.lang.String score) {
		set("score", score);
	}

	public java.lang.String getScore() {
		return get("score");
	}

	public String getScoreColumnName() {
		return "score";
	}

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}

	public java.lang.String getOrderId() {
		return get("orderId");
	}

	public String getOrderIdColumnName() {
		return "orderId";
	}

	public void setRecycleType(java.lang.String recycleType) {
		set("recycleType", recycleType);
	}

	public java.lang.String getRecycleType() {
		return get("recycleType");
	}

	public String getRecycleTypeColumnName() {
		return "recycleType";
	}

	public void setRecycleTradeAddress(java.lang.String recycleTradeAddress) {
		set("recycleTradeAddress", recycleTradeAddress);
	}

	public java.lang.String getRecycleTradeAddress() {
		return get("recycleTradeAddress");
	}

	public String getRecycleTradeAddressColumnName() {
		return "recycleTradeAddress";
	}

	public void setPrdProductId(java.lang.Integer prdProductId) {
		set("prdProductId", prdProductId);
	}

	public java.lang.Integer getPrdProductId() {
		return get("prdProductId");
	}

	public String getPrdProductIdColumnName() {
		return "prdProductId";
	}

	public void setPrdProductName(java.lang.String prdProductName) {
		set("prdProductName", prdProductName);
	}

	public java.lang.String getPrdProductName() {
		return get("prdProductName");
	}

	public String getPrdProductNameColumnName() {
		return "prdProductName";
	}

	public void setRecycleTradeAddressCity(java.lang.String recycleTradeAddressCity) {
		set("recycleTradeAddressCity", recycleTradeAddressCity);
	}

	public java.lang.String getRecycleTradeAddressCity() {
		return get("recycleTradeAddressCity");
	}

	public String getRecycleTradeAddressCityColumnName() {
		return "recycleTradeAddressCity";
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public String getRemarkColumnName() {
		return "remark";
	}

}
