package com.isongshu.huishou.skeleton.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsInfo<M extends BaseNewsInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public String getIdColumnName() {
		return "id";
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public String getTitleColumnName() {
		return "title";
	}

	public void setNewsUrl(java.lang.String newsUrl) {
		set("newsUrl", newsUrl);
	}

	public java.lang.String getNewsUrl() {
		return get("newsUrl");
	}

	public String getNewsUrlColumnName() {
		return "newsUrl";
	}

	public void setIconUrl(java.lang.String iconUrl) {
		set("iconUrl", iconUrl);
	}

	public java.lang.String getIconUrl() {
		return get("iconUrl");
	}

	public String getIconUrlColumnName() {
		return "iconUrl";
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public String getSummaryColumnName() {
		return "summary";
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public String getCreateTimeColumnName() {
		return "createTime";
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public String getContentColumnName() {
		return "content";
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public String getStatusColumnName() {
		return "status";
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public String getRemarkColumnName() {
		return "remark";
	}

}
