package com.isongshu.huishou.skeleton.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductType<M extends BaseProductType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public String getIdColumnName() {
		return "id";
	}

	public void setGoodsType(java.lang.Integer goodsType) {
		set("goodsType", goodsType);
	}

	public java.lang.Integer getGoodsType() {
		return get("goodsType");
	}

	public String getGoodsTypeColumnName() {
		return "goodsType";
	}

	public void setPrdType(java.lang.String prdType) {
		set("prdType", prdType);
	}

	public java.lang.String getPrdType() {
		return get("prdType");
	}

	public String getPrdTypeColumnName() {
		return "prdType";
	}

	public void setDescPackageId(java.lang.Integer descPackageId) {
		set("descPackageId", descPackageId);
	}

	public java.lang.Integer getDescPackageId() {
		return get("descPackageId");
	}

	public String getDescPackageIdColumnName() {
		return "descPackageId";
	}

	public void setBasePric(java.lang.Integer basePric) {
		set("basePric", basePric);
	}

	public java.lang.Integer getBasePric() {
		return get("basePric");
	}

	public String getBasePricColumnName() {
		return "basePric";
	}

	public void setHot(java.lang.String hot) {
		set("hot", hot);
	}

	public java.lang.String getHot() {
		return get("hot");
	}

	public String getHotColumnName() {
		return "hot";
	}

	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}

	public java.lang.String getFlag() {
		return get("flag");
	}

	public String getFlagColumnName() {
		return "flag";
	}

	public void setIsShow(java.lang.String isShow) {
		set("isShow", isShow);
	}

	public java.lang.String getIsShow() {
		return get("isShow");
	}

	public String getIsShowColumnName() {
		return "isShow";
	}

	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("deleteFlag", deleteFlag);
	}

	public java.lang.String getDeleteFlag() {
		return get("deleteFlag");
	}

	public String getDeleteFlagColumnName() {
		return "deleteFlag";
	}

	public void setUpdateor(java.lang.Integer updateor) {
		set("updateor", updateor);
	}

	public java.lang.Integer getUpdateor() {
		return get("updateor");
	}

	public String getUpdateorColumnName() {
		return "updateor";
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("updateTime", updateTime);
	}

	public java.lang.String getUpdateTime() {
		return get("updateTime");
	}

	public String getUpdateTimeColumnName() {
		return "updateTime";
	}

}
